# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalculatorExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Calculator', :path => '../CalculatorModule'

  target 'CalculatorExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalculatorExampleUITests' do
    # Pods for testing
  end

end
